### ISSUE TITLE
Heart Box CA

### ISSUE THREAD

**Issue by kirboatmeal** [puyogg/puyoquest-bot#15]
Summer Break Elisa's Cross Ability description incorrectly displays 1× Yellow Puyo for the activation condition instead of 1× Heart Box

**Comment by hisashiyarouin** [comment]
Argument on PuyoNexus wiki is `|caalt=h`

**Comment by s2lsoftener** [comment]
Fixed in this commit: https://github.com/puyogg/puyoquest-bot/commit/8e60fd3ec8ee91e83f3ea346c91c7c728979bd90
