### ISSUE TITLE
Capitalization error when searching for Fujiko Mine ver. PuyoQuest

### ISSUE THREAD

**Issue by kirboatmeal** [puyogg/puyoquest-bot#21]
The card "Fujiko Mine ver. PuyoQuest" cannot be retrieved because the name "Fujiko Mine ver. Puyoquest" (with a lowercase Q) is searched for instead.
[Image](https://imgur.com/a/onZUZKO)

**Comment by s2lsoftener** [comment]
Should be fixed in this commit https://github.com/puyogg/puyoquest-bot/commit/25ad08b2943f7e08376a33077a9c8f44c642bdcc
