### ISSUE TITLE
"tenroll" command throws a group of errors

### ISSUE THREAD

**Issue by Tetriser** [puyogg/puyoquest-bot#24]
![image](https://user-images.githubusercontent.com/5746458/139195821-ee2dbabd-5226-420e-8230-3ad7581a56d1.png)
I'm aware that the wiki is changing the images with the high-res ones introduced in PuyoQuest's 10.0 update, I guess

**Comment by s2lsoftener** [comment]
Fixed in https://github.com/puyogg/puyoquest-bot/commit/8e91d83a76d7dcc529a9078b2013b1ce98904f45
