### ISSUE TITLE
Massive error with pulling from Wiki

### ISSUE THREAD

**Issue by MorpheNei** [puyogg/puyoquest-bot#25]
- ?ps does not work
- ?csfancy and ?csf2 do not work
- ?c still works
- As mentioned in a previous issue, ?tenroll shows an error in fetching the card list
- ?ntc has this same error
- ?sir fails to reply 
- ?iq remains functional
- Refreshing card index with ?ri does not fix anything
- Possible other undiscovered errors
![image](https://user-images.githubusercontent.com/87589304/139505578-70ecd746-985b-481f-bc30-2c6727351a76.png)
![image](https://user-images.githubusercontent.com/87589304/139505608-6ea7de24-1290-496f-8627-c7d091647294.png)
![image](https://user-images.githubusercontent.com/87589304/139505840-056551b1-37d0-4a59-bb77-20e602863047.png)

**Comment by s2lsoftener** [comment]
fixing the way the card index gets refreshed probably fixes these issues https://github.com/puyogg/puyoquest-bot/commit/8e91d83a76d7dcc529a9078b2013b1ce98904f45
