### ISSUE TITLE
Rigged ten rolls

### ISSUE THREAD

**Issue by s2lsoftener** [puyogg/puyoquest-bot#9]
- cache the regex search when the bot starts. Have it refresh when the card index refreshes.
- Add Rozatte to the Res rigged name
- change raffina/lidelle to JustVibin
- add other sonic characters to SEGA roll

**Comment by JustVibin12** [comment]
Can you do for the name 'JustVibin' have the tenroll include Raffina, Lidelle, and Yu & Rei? Any alts will do

**Comment by TrophyHunter** [comment]
Can you do mine that has Spirit Summoners and and HDrozema and Festoll (adding the other alts is optional) Under the Name "TrophyHunter"

**Comment by Maihen2424** [comment]
Under the name "Maihen", Isin, Eridu, Rukbat, Yogi, Henriette, Melville, Komone, Taningoat, Sheepro, Töndury

**Comment by thisguyagain-24** [comment]
Under the name "Cass", the Boss!? Series + Lemres, Rafisol, Carbuncle, Ex and Doppel Arle

**Comment by s2lsoftener** [comment]
Should be done now with this commit: https://github.com/puyogg/puyoquest-bot/commit/0efe1eb10edb383be740773aeb25e7f36de9195a

**Comment by MorpheNei** [comment]
Pi - add patri to list

**Comment by Chuuly10** [comment]
Okay okay— uh— okay this is stupid but can we have a roll where if you’re named like “Todomatsu” or smthn it’s just all the ososan collab characters. 

Yeah. 

Both the real Matsus, the puyo matsus, and totoko ig.

**Comment by SuperLuigEthan** [comment]
Under the name “Super LuigEthan”, Scorched Desert Journey and Nature Braver SDJ series, Artisan Series and Klug, please.

**Comment by noroikishi** [comment]
for "luna" (including stuff after it if thats ok lol) - hilda, eldur, wacht, pitch-black wacht, friede, crowlas, and mappela thank you 🙏

**Comment by solipsplosion** [comment]
Hi I know you already added Rozatte to Res but only if you want to I'd like if you could put Bestoll and Felix in there (only do this if it's not hard because I feel bad)

**Comment by kirboatmeal** [comment]
Under the name "Kirub", Artisan series (with Sharky Michelo when she's implemented), Accursed Knight series (with Crowlas and Pitch-black Wacht), Sage series, Sage of Verity series, and Albert
Thank you so much 🙇‍♂️

**Comment by s2lsoftener** [comment]
Finished in this commit: https://github.com/puyogg/puyoquest-bot/commit/3a5f85f991c6229995f2cd3a45322914eaee61f0

I won't be doing any more updates unless you're a wiki editor on EPPC and you DM me about it. I'll be more focused on an api/bot rewrite.
